# Generated by Django 4.0.3 on 2022-03-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHandler',
            fields=[
                ('id', models.CharField(default=0, max_length=10, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='files')),
            ],
        ),
    ]
