# Generated by Django 4.0.3 on 2022-03-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='response',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default='works!', max_length=101),
        ),
    ]
