# Generated by Django 4.0.3 on 2022-03-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_testmodel_response_testmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehandler',
            name='image',
            field=models.ImageField(blank=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(max_length=101),
        ),
    ]
