# Generated by Django 4.0.3 on 2022-03-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_imagehandler_image_alter_testmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehandler',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
