# Generated by Django 4.0.3 on 2022-03-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_imagehandler_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehandler',
            name='image',
        ),
        migrations.AddField(
            model_name='imagehandler',
            name='Image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
