# Generated by Django 4.0.3 on 2022-03-12 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_remove_imagehandler_image_imagehandler_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagehandler',
            old_name='Image',
            new_name='image',
        ),
    ]
