# Generated by Django 4.0.3 on 2022-03-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_rename_image_imagehandler_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehandler',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
