# Generated by Django 4.0.3 on 2022-03-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_alter_imagehandler_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehandler',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
