# Generated by Django 4.0.3 on 2022-03-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_alter_imagehandler_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredicionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preds', models.DecimalField(decimal_places=5, default=0.0, max_digits=13)),
            ],
        ),
    ]
