# Generated by Django 4.0.3 on 2022-03-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_predicionsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredicionsModel',
            new_name='PredictionsModel',
        ),
    ]
