# Generated by Django 4.0.3 on 2022-05-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_rename_predicionsmodel_predictionsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionsmodel',
            name='probability',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='predictionsmodel',
            name='preds',
            field=models.CharField(max_length=101),
        ),
    ]
