# Generated by Django 4.0.3 on 2022-05-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_predictionsmodel_probability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionsmodel',
            name='probability',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=32),
        ),
    ]
