# Generated by Django 4.0.3 on 2022-05-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_alter_predictionsmodel_probability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionsmodel',
            name='probability',
        ),
        migrations.AlterField(
            model_name='predictionsmodel',
            name='preds',
            field=models.DecimalField(decimal_places=32, default=0.0, max_digits=34),
        ),
    ]
